rules:
  excessive-permissions:
    ignore:
      - scorecard.yml:12
  dangerous-triggers:
    ignore:
      - labeler.yml:2
  cache-poisoning:
    # https://github.com/zizmorcore/zizmor/issues/2071
    ignore:
      - full-build.yml:314
      - full-build.yml:345
      - full-build.yml:349
