version: 2
formats: all
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  apt_packages:
  - libgirepository1.0-dev
  - gir1.2-pango-1.0
  - gir1.2-gtk-3.0
  - gir1.2-gtksource-4  
sphinx:
  configuration: docs/conf.py
python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
