version: 2
formats:
  - htmlzip
  - epub
build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest
    install:
      - pixi install -e docs
    build:
      html:
        - pixi run rtd-html
      epub:
        - pixi run rtd-epub
      htmlzip:
        - pixi run rtd-htmlzip
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
