Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
config.vm.provider "virtualbox" do |vb|
  vb.gui = true
  vb.memory = "1024"
end
config.vm.synced_folder '../..', '/home/vagrant/gaphor'

config.vm.provision "shell", inline: <<-SHELL
  pacman -Syu --noconfirm
  pacman -Sy --noconfirm xorg-server xf86-video-vmware xorg-xinit
  pacman -Sy --noconfirm lxde-gtk3 lxdm-gtk3 
  systemctl enable lxdm.service
  pacman -S --noconfirm virtualbox-guest-utils virtualbox-guest-dkms
  pacman -S --noconfirm cairo pkgconf gobject-introspection git base-devel
  pacman -S --noconfirm python-pip
  pip install poetry

SHELL
end
