# This file is generated by coder.py. DO NOT EDIT!
# ruff: noqa: F401, E402, F811
# fmt: off

from __future__ import annotations

import enum

from gaphor.core.modeling.properties import (
    association,
    attribute as _attribute,
    derived,
    derivedunion,
    enumeration as _enumeration,
    redefine,
    relation_many,
    relation_one,
    subset,
)


from gaphor.KerML.kerml import Classifier as _Classifier
from gaphor.KerML.kerml import Class as _Class
from gaphor.KerML.kerml import Behavior as _Behavior
from gaphor.KerML.kerml import Interaction as _Interaction
from gaphor.KerML.kerml import Feature as _Feature
from gaphor.KerML.kerml import Connector as _Connector
from gaphor.KerML.kerml import Flow as _Flow
from gaphor.KerML.kerml import Step as _Step
from gaphor.KerML.kerml import SuccessionFlow as _SuccessionFlow
from gaphor.KerML.kerml import DataType as _DataType
from gaphor.KerML.kerml import BooleanExpression as _BooleanExpression
from gaphor.KerML.kerml import FeatureMembership as _FeatureMembership
from gaphor.KerML.kerml import ParameterMembership as _ParameterMembership
from gaphor.KerML.kerml import Predicate as _Predicate
from gaphor.KerML.kerml import Invariant as _Invariant
from gaphor.KerML.kerml import Function as _Function
from gaphor.KerML.kerml import Expression as _Expression
from gaphor.KerML.kerml import Structure as _Structure
from gaphor.KerML.kerml import Metaclass as _Metaclass
from gaphor.KerML.kerml import MetadataFeature as _MetadataFeature
from gaphor.KerML.kerml import InvocationExpression as _InvocationExpression
from gaphor.KerML.kerml import OwningMembership as _OwningMembership
from gaphor.KerML.kerml import Conjugation as _Conjugation
from gaphor.KerML.kerml import FeatureTyping as _FeatureTyping
from gaphor.KerML.kerml import Import as _Import
from gaphor.KerML.kerml import MembershipImport as _MembershipImport
from gaphor.KerML.kerml import NamespaceImport as _NamespaceImport
from gaphor.KerML.kerml import Succession as _Succession
from gaphor.KerML.kerml import AssociationStructure as _AssociationStructure
from gaphor.KerML.kerml import BindingConnector as _BindingConnector
from gaphor.KerML.kerml import Association as _Association
from gaphor.KerML.kerml import Element as _Element
from gaphor.KerML.kerml import Type as _Type
from gaphor.KerML.kerml import Namespace as _Namespace
from gaphor.KerML.kerml import Membership as _Membership
from gaphor.KerML.kerml import Specialization as _Specialization
from gaphor.KerML.kerml import VisibilityKind as _VisibilityKind


class PortionKind(enum.StrEnum):
    timeslice = "timeslice"
    snapshot = "snapshot"


class RequirementConstraintKind(enum.StrEnum):
    assumption = "assumption"
    requirement = "requirement"


class StateSubactionKind(enum.StrEnum):
    entry = "entry"
    do = "do"
    exit = "exit"


class TransitionFeatureKind(enum.StrEnum):
    trigger = "trigger"
    guard = "guard"
    effect = "effect"


class TriggerKind(enum.StrEnum):
    when = "when"
    at = "at"
    after = "after"


class Definition(_Classifier):
    directedUsage: relation_many[Usage]
    isVariation: _attribute[bool] = _attribute("isVariation", bool)
    ownedAction: relation_many[ActionUsage]
    ownedAllocation: relation_many[AllocationUsage]
    ownedAnalysisCase: relation_many[AnalysisCaseUsage]
    ownedAttribute: relation_many[AttributeUsage]
    ownedCalculation: relation_many[CalculationUsage]
    ownedCase: relation_many[CaseUsage]
    ownedConcern: relation_many[ConcernUsage]
    ownedConnection: relation_many[ConnectorAsUsage]
    ownedConstraint: relation_many[ConstraintUsage]
    ownedEnumeration: relation_many[EnumerationUsage]
    ownedFlow: relation_many[FlowUsage]
    ownedInterface: relation_many[InterfaceUsage]
    ownedItem: relation_many[ItemUsage]
    ownedMetadata: relation_many[MetadataUsage]
    ownedOccurrence: relation_many[OccurrenceUsage]
    ownedPart: relation_many[PartUsage]
    ownedPort: relation_many[PortUsage]
    ownedReference: relation_many[ReferenceUsage]
    ownedRendering: relation_many[RenderingUsage]
    ownedRequirement: relation_many[RequirementUsage]
    ownedState: relation_many[StateUsage]
    ownedTransition: relation_many[TransitionUsage]
    ownedUsage: relation_many[Usage]
    ownedUseCase: relation_many[UseCaseUsage]
    ownedVerificationCase: relation_many[VerificationCaseUsage]
    ownedView: relation_many[ViewUsage]
    ownedViewpoint: relation_many[ViewpointUsage]
    usage: relation_many[Usage]
    variant: relation_many[Usage]
    variantMembership: relation_many[VariantMembership]


class OccurrenceDefinition(Definition, _Class):
    isIndividual: _attribute[bool] = _attribute("isIndividual", bool, default=False)


class ActionDefinition(OccurrenceDefinition, _Behavior):
    action: relation_many[ActionUsage]


class FlowDefinition(ActionDefinition, _Interaction):
    flowEnd: relation_many[Usage]


class Usage(_Feature):
    definition: relation_many[_Classifier]
    directedUsage: relation_many[Usage]
    isVariation: _attribute[bool] = _attribute("isVariation", bool)
    nestedAction: relation_many[ActionUsage]
    nestedAllocation: relation_many[AllocationUsage]
    nestedAnalysisCase: relation_many[AnalysisCaseUsage]
    nestedAttribute: relation_many[AttributeUsage]
    nestedCalculation: relation_many[CalculationUsage]
    nestedCase: relation_many[CaseUsage]
    nestedConcern: relation_many[ConcernUsage]
    nestedConnection: relation_many[ConnectorAsUsage]
    nestedConstraint: relation_many[ConstraintUsage]
    nestedEnumeration: relation_many[EnumerationUsage]
    nestedFlow: relation_many[FlowUsage]
    nestedInterface: relation_many[InterfaceUsage]
    nestedItem: relation_many[ItemUsage]
    nestedMetadata: relation_many[MetadataUsage]
    nestedOccurrence: relation_many[OccurrenceUsage]
    nestedPart: relation_many[PartUsage]
    nestedPort: relation_many[PortUsage]
    nestedReference: relation_many[ReferenceUsage]
    nestedRendering: relation_many[RenderingUsage]
    nestedRequirement: relation_many[RequirementUsage]
    nestedState: relation_many[StateUsage]
    nestedTransition: relation_many[TransitionUsage]
    nestedUsage: relation_many[Usage]
    nestedUseCase: relation_many[UseCaseUsage]
    nestedVerificationCase: relation_many[VerificationCaseUsage]
    nestedView: relation_many[ViewUsage]
    nestedViewpoint: relation_many[ViewpointUsage]
    owningDefinition: relation_one[Definition]
    owningUsage: relation_one[Usage]
    usage: relation_many[Usage]
    variant: relation_many[Usage]
    variantMembership: relation_many[VariantMembership]


class ConnectorAsUsage(Usage, _Connector):
    pass


class OccurrenceUsage(Usage):
    individualDefinition: relation_one[OccurrenceDefinition]
    isIndividual: _attribute[bool] = _attribute("isIndividual", bool, default=False)
    occurrenceDefinition: relation_many[_Class]
    portionKind = _enumeration("portionKind", PortionKind, PortionKind.timeslice)


class ActionUsage(OccurrenceUsage, _Step):
    actionDefinition: relation_many[_Behavior]


class FlowUsage(ActionUsage, ConnectorAsUsage, _Flow):
    flowDefinition: relation_many[_Interaction]


class SuccessionFlowUsage(FlowUsage, _SuccessionFlow):
    pass


class AttributeDefinition(Definition, _DataType):
    pass


class EnumerationDefinition(AttributeDefinition):
    enumeratedValue: relation_many[EnumerationUsage]
    isVariation: _attribute[bool] = _attribute("isVariation", bool, default=False)


class AttributeUsage(Usage):
    attributeDefinition: relation_many[_DataType]


class EnumerationUsage(AttributeUsage):
    enumerationDefinition: relation_one[EnumerationDefinition]


class ConstraintUsage(OccurrenceUsage, _BooleanExpression):
    constraintDefinition: relation_one[_Predicate]


class RequirementUsage(ConstraintUsage):
    actorParameter: relation_many[PartUsage]
    assumedConstraint: relation_many[ConstraintUsage]
    framedConcern: relation_many[ConcernUsage]
    reqId: _attribute[str] = _attribute("reqId", str)
    requiredConstraint: relation_many[ConstraintUsage]
    requirementDefinition: relation_one[RequirementDefinition]
    stakeholderParameter: relation_many[PartUsage]
    subjectParameter: relation_one[Usage]


class ConcernUsage(RequirementUsage):
    concernDefinition: relation_one[ConcernDefinition]


class RequirementConstraintMembership(_FeatureMembership):
    kind = _enumeration("kind", RequirementConstraintKind, RequirementConstraintKind.assumption)
    ownedConstraint: relation_one[ConstraintUsage]
    referencedConstraint: relation_one[ConstraintUsage]


class FramedConcernMembership(RequirementConstraintMembership):
    kind = _enumeration("kind", RequirementConstraintKind, RequirementConstraintKind.assumption)
    ownedConcern: relation_one[ConcernUsage]
    referencedConcern: relation_one[ConcernUsage]


class ActorMembership(_ParameterMembership):
    ownedActorParameter: relation_one[PartUsage]


class StakeholderMembership(_ParameterMembership):
    ownedStakeholderParameter: relation_one[PartUsage]


class SubjectMembership(_ParameterMembership):
    ownedSubjectParameter: relation_one[Usage]


class ConstraintDefinition(OccurrenceDefinition, _Predicate):
    pass


class RequirementDefinition(ConstraintDefinition):
    actorParameter: relation_many[PartUsage]
    assumedConstraint: relation_many[ConstraintUsage]
    framedConcern: relation_many[ConcernUsage]
    reqId: _attribute[str] = _attribute("reqId", str)
    requiredConstraint: relation_many[ConstraintUsage]
    stakeholderParameter: relation_many[PartUsage]
    subjectParameter: relation_one[Usage]


class ConcernDefinition(RequirementDefinition):
    pass


class AssertConstraintUsage(ConstraintUsage, _Invariant):
    assertedConstraint: relation_one[ConstraintUsage]


class SatisfyRequirementUsage(AssertConstraintUsage, RequirementUsage):
    satisfiedRequirement: relation_one[RequirementUsage]
    satisfyingFeature: relation_one[_Feature]


class CalculationDefinition(ActionDefinition, _Function):
    calculation: relation_many[CalculationUsage]


class CalculationUsage(ActionUsage, _Expression):
    calculationDefinition: relation_one[_Function]


class ItemDefinition(OccurrenceDefinition, _Structure):
    pass


class MetadataDefinition(ItemDefinition, _Metaclass):
    pass


class ItemUsage(OccurrenceUsage):
    itemDefinition: relation_many[_Structure]


class MetadataUsage(ItemUsage, _MetadataFeature):
    metadataDefinition: relation_one[_Metaclass]


class CaseUsage(CalculationUsage):
    actorParameter: relation_many[PartUsage]
    caseDefinition: relation_one[CaseDefinition]
    objectiveRequirement: relation_one[RequirementUsage]
    subjectParameter: relation_one[Usage]


class CaseDefinition(CalculationDefinition):
    actorParameter: relation_many[PartUsage]
    objectiveRequirement: relation_one[RequirementUsage]
    subjectParameter: relation_one[Usage]


class ObjectiveMembership(_FeatureMembership):
    ownedObjectiveRequirement: relation_one[RequirementUsage]


class TransitionFeatureMembership(_FeatureMembership):
    kind = _enumeration("kind", TransitionFeatureKind, TransitionFeatureKind.trigger)
    transitionFeature: relation_one[_Step]


class EventOccurrenceUsage(OccurrenceUsage):
    eventOccurrence: relation_one[OccurrenceUsage]


class PerformActionUsage(ActionUsage, EventOccurrenceUsage):
    performedAction: relation_one[ActionUsage]


class StateUsage(ActionUsage):
    doAction: relation_one[ActionUsage]
    entryAction: relation_one[ActionUsage]
    exitAction: relation_one[ActionUsage]
    isParallel: _attribute[bool] = _attribute("isParallel", bool, default=False)
    stateDefinition: relation_many[_Behavior]


class ExhibitStateUsage(PerformActionUsage, StateUsage):
    exhibitedState: relation_one[StateUsage]


class StateSubactionMembership(_FeatureMembership):
    action: relation_one[ActionUsage]
    kind = _enumeration("kind", StateSubactionKind, StateSubactionKind.entry)


class StateDefinition(ActionDefinition):
    doAction: relation_one[ActionUsage]
    entryAction: relation_one[ActionUsage]
    exitAction: relation_one[ActionUsage]
    isParallel: _attribute[bool] = _attribute("isParallel", bool, default=False)
    state: relation_many[StateUsage]


class TransitionUsage(ActionUsage):
    effectAction: relation_many[ActionUsage]
    guardExpression: relation_many[_Expression]
    source: relation_one[ActionUsage]
    succession: relation_one[_Succession]
    target: relation_one[ActionUsage]
    triggerAction: relation_many[AcceptActionUsage]


class UseCaseUsage(CaseUsage):
    includedUseCase: relation_many[UseCaseUsage]
    useCaseDefinition: relation_one[UseCaseDefinition]


class IncludeUseCaseUsage(PerformActionUsage, UseCaseUsage):
    useCaseIncluded: relation_one[UseCaseUsage]


class UseCaseDefinition(CaseDefinition):
    includedUseCase: relation_many[UseCaseUsage]


class AssignmentActionUsage(ActionUsage):
    referent: relation_one[_Feature]
    targetArgument: relation_one[_Expression]
    valueExpression: relation_one[_Expression]


class LoopActionUsage(ActionUsage):
    bodyAction: relation_one[ActionUsage]


class ForLoopActionUsage(LoopActionUsage):
    loopVariable: relation_one[ReferenceUsage]
    seqArgument: relation_one[_Expression]


class TriggerInvocationExpression(_InvocationExpression):
    kind = _enumeration("kind", TriggerKind, TriggerKind.when)


class ControlNode(ActionUsage):
    pass


class DecisionNode(ControlNode):
    pass


class ForkNode(ControlNode):
    pass


class JoinNode(ControlNode):
    pass


class MergeNode(ControlNode):
    pass


class TerminateActionUsage(ActionUsage):
    terminatedOccurrenceArgument: relation_one[_Expression]


class AcceptActionUsage(ActionUsage):
    payloadArgument: relation_one[_Expression]
    payloadParameter: relation_one[ReferenceUsage]
    receiverArgument: relation_one[_Expression]


class WhileLoopActionUsage(LoopActionUsage):
    untilArgument: relation_one[_Expression]
    whileArgument: relation_one[_Expression]


class SendActionUsage(ActionUsage):
    payloadArgument: relation_one[_Expression]
    receiverArgument: relation_one[_Expression]
    senderArgument: relation_one[_Expression]


class IfActionUsage(ActionUsage):
    elseAction: relation_one[ActionUsage]
    ifArgument: relation_one[_Expression]
    thenAction: relation_one[ActionUsage]


class ReferenceUsage(Usage):
    pass


class VariantMembership(_OwningMembership):
    ownedVariantUsage: relation_one[Usage]


class PartDefinition(ItemDefinition):
    pass


class PartUsage(ItemUsage):
    partDefinition: relation_many[PartDefinition]


class AnalysisCaseUsage(CaseUsage):
    analysisCaseDefinition: relation_one[AnalysisCaseDefinition]
    resultExpression: relation_one[_Expression]


class AnalysisCaseDefinition(CaseDefinition):
    resultExpression: relation_one[_Expression]


class PortConjugation(_Conjugation):
    conjugatedPortDefinition: relation_one[ConjugatedPortDefinition]
    originalPortDefinition: relation_one[PortDefinition]


class PortDefinition(OccurrenceDefinition, _Structure):
    conjugatedPortDefinition: relation_one[ConjugatedPortDefinition]


class ConjugatedPortDefinition(PortDefinition):
    originalPortDefinition: relation_one[PortDefinition]
    ownedPortConjugator: relation_one[PortConjugation]


class ConjugatedPortTyping(_FeatureTyping):
    conjugatedPortDefinition: relation_one[ConjugatedPortDefinition]
    portDefinition: relation_one[PortDefinition]


class PortUsage(OccurrenceUsage):
    portDefinition: relation_many[PortDefinition]


class ViewUsage(PartUsage):
    exposedElement: relation_many[_Element]
    satisfiedViewpoint: relation_many[ViewpointUsage]
    viewCondition: relation_many[_Expression]
    viewDefinition: relation_one[ViewDefinition]
    viewRendering: relation_one[RenderingUsage]


class Expose(_Import):
    isImportAll: _attribute[bool] = _attribute("isImportAll", bool, default=False)


class ViewDefinition(PartDefinition):
    satisfiedViewpoint: relation_many[ViewpointUsage]
    view: relation_many[ViewUsage]
    viewCondition: relation_many[_Expression]
    viewRendering: relation_one[RenderingUsage]


class RenderingUsage(PartUsage):
    renderingDefinition: relation_one[RenderingDefinition]


class ViewpointDefinition(RequirementDefinition):
    viewpointStakeholder: relation_many[PartUsage]


class RenderingDefinition(PartDefinition):
    rendering: relation_many[RenderingUsage]


class MembershipExpose(Expose, _MembershipImport):
    pass


class NamespaceExpose(Expose, _NamespaceImport):
    pass


class ViewRenderingMembership(_FeatureMembership):
    ownedRendering: relation_one[RenderingUsage]
    referencedRendering: relation_one[RenderingUsage]


class ViewpointUsage(RequirementUsage):
    viewpointDefinition: relation_one[ViewpointDefinition]
    viewpointStakeholder: relation_many[PartUsage]


class ConnectionUsage(ConnectorAsUsage, PartUsage):
    connectionDefinition: relation_many[_AssociationStructure]


class SuccessionAsUsage(ConnectorAsUsage, _Succession):
    pass


class ConnectionDefinition(PartDefinition, _AssociationStructure):
    connectionEnd: relation_many[Usage]
    isSufficient: _attribute[bool] = _attribute("isSufficient", bool, default=False)


class BindingConnectorAsUsage(ConnectorAsUsage, _BindingConnector):
    pass


class InterfaceUsage(ConnectionUsage):
    interfaceDefinition: relation_many[InterfaceDefinition]


class InterfaceDefinition(ConnectionDefinition):
    interfaceEnd: relation_many[PortUsage]


class AllocationDefinition(ConnectionDefinition):
    allocation: relation_many[AllocationUsage]


class AllocationUsage(ConnectionUsage):
    allocationDefinition: relation_many[AllocationDefinition]


class RequirementVerificationMembership(RequirementConstraintMembership):
    kind = _enumeration("kind", RequirementConstraintKind, RequirementConstraintKind.assumption)
    ownedRequirement: relation_one[RequirementUsage]
    verifiedRequirement: relation_one[RequirementUsage]


class VerificationCaseDefinition(CaseDefinition):
    verifiedRequirement: relation_many[RequirementUsage]


class VerificationCaseUsage(CaseUsage):
    verificationCaseDefinition: relation_one[VerificationCaseDefinition]
    verifiedRequirement: relation_many[RequirementUsage]



Definition.variant = subset("variant", Usage, 0, '*', None, _Namespace.ownedMember)
Definition.variantMembership = subset("variantMembership", VariantMembership, 0, '*', None, _Namespace.ownedMembership)
Definition.usage = subset("usage", Usage, 0, '*', None, _Type.feature)
Definition.directedUsage = subset("directedUsage", Usage, 0, '*', None, _Type.directedFeature, Definition.usage)
Definition.ownedUsage = subset("ownedUsage", Usage, 0, '*', None, _Type.ownedFeature, Definition.usage)
Definition.ownedReference = subset("ownedReference", ReferenceUsage, 0, '*', None, Definition.ownedUsage)
Definition.ownedAttribute = subset("ownedAttribute", AttributeUsage, 0, '*', None, Definition.ownedUsage)
Definition.ownedOccurrence = subset("ownedOccurrence", OccurrenceUsage, 0, '*', None, Definition.ownedUsage)
Definition.ownedPort = subset("ownedPort", PortUsage, 0, '*', None, Definition.ownedUsage)
Definition.ownedConnection = subset("ownedConnection", ConnectorAsUsage, 0, '*', None, Definition.ownedUsage)
Definition.ownedTransition = subset("ownedTransition", TransitionUsage, 0, '*', None, Definition.ownedUsage)
Definition.ownedEnumeration = subset("ownedEnumeration", EnumerationUsage, 0, '*', None, Definition.ownedAttribute)
Definition.ownedItem = subset("ownedItem", ItemUsage, 0, '*', None, Definition.ownedOccurrence)
Definition.ownedFlow = subset("ownedFlow", FlowUsage, 0, '*', None, Definition.ownedConnection)
Definition.ownedInterface = subset("ownedInterface", InterfaceUsage, 0, '*', None, Definition.ownedConnection)
Definition.ownedAllocation = subset("ownedAllocation", AllocationUsage, 0, '*', None, Definition.ownedConnection)
Definition.ownedAction = subset("ownedAction", ActionUsage, 0, '*', None, Definition.ownedOccurrence)
Definition.ownedConstraint = subset("ownedConstraint", ConstraintUsage, 0, '*', None, Definition.ownedOccurrence)
Definition.ownedPart = subset("ownedPart", PartUsage, 0, '*', None, Definition.ownedItem)
Definition.ownedState = subset("ownedState", StateUsage, 0, '*', None, Definition.ownedAction)
Definition.ownedCalculation = subset("ownedCalculation", CalculationUsage, 0, '*', None, Definition.ownedAction)
Definition.ownedRequirement = subset("ownedRequirement", RequirementUsage, 0, '*', None, Definition.ownedConstraint)
Definition.ownedMetadata = subset("ownedMetadata", MetadataUsage, 0, '*', None, Definition.ownedItem)
Definition.ownedConcern = subset("ownedConcern", ConcernUsage, 0, '*', None, Definition.ownedRequirement)
Definition.ownedCase = subset("ownedCase", CaseUsage, 0, '*', None, Definition.ownedCalculation)
Definition.ownedView = subset("ownedView", ViewUsage, 0, '*', None, Definition.ownedPart)
Definition.ownedViewpoint = subset("ownedViewpoint", ViewpointUsage, 0, '*', None, Definition.ownedRequirement)
Definition.ownedRendering = subset("ownedRendering", RenderingUsage, 0, '*', None, Definition.ownedPart)
Definition.ownedAnalysisCase = subset("ownedAnalysisCase", AnalysisCaseUsage, 0, '*', None, Definition.ownedCase)
Definition.ownedVerificationCase = subset("ownedVerificationCase", VerificationCaseUsage, 0, '*', None, Definition.ownedCase)
Definition.ownedUseCase = subset("ownedUseCase", UseCaseUsage, 0, '*', None, Definition.ownedCase)
ActionDefinition.action = subset("action", ActionUsage, 0, '*', None, _Behavior.step, Definition.usage)
FlowDefinition.flowEnd = redefine(FlowDefinition, "flowEnd", Usage, _Association.associationEnd)
Usage.definition = redefine(Usage, "definition", _Classifier, _Feature.type)
Usage.variant = subset("variant", Usage, 0, '*', None, _Namespace.ownedMember)
Usage.variantMembership = subset("variantMembership", VariantMembership, 0, '*', None, _Namespace.ownedMembership)
Usage.owningDefinition = subset("owningDefinition", Definition, 0, 1, None, _Feature.owningType)
Usage.owningUsage = subset("owningUsage", Usage, 0, 1, None, _Feature.owningType)
Usage.usage = subset("usage", Usage, 0, '*', None, _Type.feature)
Usage.directedUsage = subset("directedUsage", Usage, 0, '*', None, _Type.directedFeature, Usage.usage)
Usage.nestedUsage = subset("nestedUsage", Usage, 0, '*', None, _Type.ownedFeature, Usage.usage)
Usage.nestedReference = subset("nestedReference", ReferenceUsage, 0, '*', None, Usage.nestedUsage)
Usage.nestedAttribute = subset("nestedAttribute", AttributeUsage, 0, '*', None, Usage.nestedUsage)
Usage.nestedOccurrence = subset("nestedOccurrence", OccurrenceUsage, 0, '*', None, Usage.nestedUsage)
Usage.nestedPort = subset("nestedPort", PortUsage, 0, '*', None, Usage.nestedUsage)
Usage.nestedConnection = subset("nestedConnection", ConnectorAsUsage, 0, '*', None, Usage.nestedUsage)
Usage.nestedTransition = subset("nestedTransition", TransitionUsage, 0, '*', None, Usage.nestedUsage)
Usage.nestedEnumeration = subset("nestedEnumeration", EnumerationUsage, 0, '*', None, Usage.nestedAttribute)
Usage.nestedItem = subset("nestedItem", ItemUsage, 0, '*', None, Usage.nestedOccurrence)
Usage.nestedFlow = subset("nestedFlow", FlowUsage, 0, '*', None, Usage.nestedConnection)
Usage.nestedInterface = subset("nestedInterface", InterfaceUsage, 0, '*', None, Usage.nestedConnection)
Usage.nestedAllocation = subset("nestedAllocation", AllocationUsage, 0, '*', None, Usage.nestedConnection)
Usage.nestedAction = subset("nestedAction", ActionUsage, 0, '*', None, Usage.nestedOccurrence)
Usage.nestedConstraint = subset("nestedConstraint", ConstraintUsage, 0, '*', None, Usage.nestedOccurrence)
Usage.nestedPart = subset("nestedPart", PartUsage, 0, '*', None, Usage.nestedItem)
Usage.nestedState = subset("nestedState", StateUsage, 0, '*', None, Usage.nestedAction)
Usage.nestedCalculation = subset("nestedCalculation", CalculationUsage, 0, '*', None, Usage.nestedAction)
Usage.nestedRequirement = subset("nestedRequirement", RequirementUsage, 0, '*', None, Usage.nestedConstraint)
Usage.nestedMetadata = subset("nestedMetadata", MetadataUsage, 0, '*', None, Usage.nestedItem)
Usage.nestedConcern = subset("nestedConcern", ConcernUsage, 0, '*', None, Usage.nestedRequirement)
Usage.nestedCase = subset("nestedCase", CaseUsage, 0, '*', None, Usage.nestedCalculation)
Usage.nestedView = subset("nestedView", ViewUsage, 0, '*', None, Usage.nestedPart)
Usage.nestedViewpoint = subset("nestedViewpoint", ViewpointUsage, 0, '*', None, Usage.nestedRequirement)
Usage.nestedRendering = subset("nestedRendering", RenderingUsage, 0, '*', None, Usage.nestedPart)
Usage.nestedAnalysisCase = subset("nestedAnalysisCase", AnalysisCaseUsage, 0, '*', None, Usage.nestedCase)
Usage.nestedVerificationCase = subset("nestedVerificationCase", VerificationCaseUsage, 0, '*', None, Usage.nestedCase)
Usage.nestedUseCase = subset("nestedUseCase", UseCaseUsage, 0, '*', None, Usage.nestedCase)
OccurrenceUsage.occurrenceDefinition = redefine(OccurrenceUsage, "occurrenceDefinition", _Class, Usage.definition)
OccurrenceUsage.individualDefinition = subset("individualDefinition", OccurrenceDefinition, 0, 1, None, OccurrenceUsage.occurrenceDefinition)
ActionUsage.actionDefinition = redefine(ActionUsage, "actionDefinition", _Behavior, _Step.behavior)
FlowUsage.flowDefinition = redefine(FlowUsage, "flowDefinition", _Interaction, ActionUsage.actionDefinition)
EnumerationDefinition.enumeratedValue = redefine(EnumerationDefinition, "enumeratedValue", EnumerationUsage, Definition.variant)
AttributeUsage.attributeDefinition = redefine(AttributeUsage, "attributeDefinition", _DataType, Usage.definition)
EnumerationUsage.enumerationDefinition = redefine(EnumerationUsage, "enumerationDefinition", EnumerationDefinition, AttributeUsage.attributeDefinition)
ConstraintUsage.constraintDefinition = redefine(ConstraintUsage, "constraintDefinition", _Predicate, _BooleanExpression.predicate)
RequirementUsage.requirementDefinition = redefine(RequirementUsage, "requirementDefinition", RequirementDefinition, ConstraintUsage.constraintDefinition)
RequirementUsage.requiredConstraint = subset("requiredConstraint", ConstraintUsage, 0, '*', None, _Type.ownedFeature)
RequirementUsage.assumedConstraint = subset("assumedConstraint", ConstraintUsage, 0, '*', None, _Type.ownedFeature)
RequirementUsage.subjectParameter = subset("subjectParameter", Usage, 1, 1, None, _Step.parameter, Usage.usage)
RequirementUsage.actorParameter = subset("actorParameter", PartUsage, 0, '*', None, _Step.parameter, Usage.usage)
RequirementUsage.stakeholderParameter = subset("stakeholderParameter", PartUsage, 0, '*', None, _Step.parameter, Usage.usage)
RequirementUsage.framedConcern = subset("framedConcern", ConcernUsage, 0, '*', None, RequirementUsage.requiredConstraint)
ConcernUsage.concernDefinition = redefine(ConcernUsage, "concernDefinition", ConcernDefinition, RequirementUsage.requirementDefinition)
RequirementConstraintMembership.referencedConstraint = derivedunion("referencedConstraint", ConstraintUsage, lower=1, upper=1)
RequirementConstraintMembership.ownedConstraint = redefine(RequirementConstraintMembership, "ownedConstraint", ConstraintUsage, _FeatureMembership.ownedMemberFeature)
FramedConcernMembership.ownedConcern = redefine(FramedConcernMembership, "ownedConcern", ConcernUsage, RequirementConstraintMembership.ownedConstraint)
FramedConcernMembership.referencedConcern = redefine(FramedConcernMembership, "referencedConcern", ConcernUsage, RequirementConstraintMembership.referencedConstraint)
ActorMembership.ownedActorParameter = redefine(ActorMembership, "ownedActorParameter", PartUsage, _ParameterMembership.ownedMemberParameter)
StakeholderMembership.ownedStakeholderParameter = redefine(StakeholderMembership, "ownedStakeholderParameter", PartUsage, _ParameterMembership.ownedMemberParameter)
SubjectMembership.ownedSubjectParameter = redefine(SubjectMembership, "ownedSubjectParameter", Usage, _ParameterMembership.ownedMemberParameter)
RequirementDefinition.subjectParameter = subset("subjectParameter", Usage, 1, 1, None, _Behavior.parameter, Definition.usage)
RequirementDefinition.actorParameter = subset("actorParameter", PartUsage, 0, '*', None, _Behavior.parameter, Definition.usage)
RequirementDefinition.stakeholderParameter = subset("stakeholderParameter", PartUsage, 0, '*', None, _Behavior.parameter, Definition.usage)
RequirementDefinition.assumedConstraint = subset("assumedConstraint", ConstraintUsage, 0, '*', None, _Type.ownedFeature)
RequirementDefinition.requiredConstraint = subset("requiredConstraint", ConstraintUsage, 0, '*', None, _Type.ownedFeature)
RequirementDefinition.framedConcern = subset("framedConcern", ConcernUsage, 0, '*', None, RequirementDefinition.requiredConstraint)
AssertConstraintUsage.assertedConstraint = derivedunion("assertedConstraint", ConstraintUsage, lower=1, upper=1)
SatisfyRequirementUsage.satisfyingFeature = derivedunion("satisfyingFeature", _Feature, lower=1, upper=1)
SatisfyRequirementUsage.satisfiedRequirement = redefine(SatisfyRequirementUsage, "satisfiedRequirement", RequirementUsage, AssertConstraintUsage.assertedConstraint)
CalculationDefinition.calculation = subset("calculation", CalculationUsage, 0, '*', None, ActionDefinition.action, _Function.expression)
CalculationUsage.calculationDefinition = redefine(CalculationUsage, "calculationDefinition", _Function, _Expression.function)
ItemUsage.itemDefinition = subset("itemDefinition", _Structure, 0, '*', None, OccurrenceUsage.occurrenceDefinition)
MetadataUsage.metadataDefinition = redefine(MetadataUsage, "metadataDefinition", _Metaclass, ItemUsage.itemDefinition)
CaseUsage.caseDefinition = redefine(CaseUsage, "caseDefinition", CaseDefinition, CalculationUsage.calculationDefinition)
CaseUsage.objectiveRequirement = subset("objectiveRequirement", RequirementUsage, 0, 1, None, Usage.usage)
CaseUsage.subjectParameter = subset("subjectParameter", Usage, 1, 1, None, _Step.parameter, Usage.usage)
CaseUsage.actorParameter = subset("actorParameter", PartUsage, 0, '*', None, _Step.parameter, Usage.usage)
CaseDefinition.objectiveRequirement = subset("objectiveRequirement", RequirementUsage, 0, 1, None, Definition.usage)
CaseDefinition.subjectParameter = subset("subjectParameter", Usage, 1, 1, None, _Behavior.parameter, Definition.usage)
CaseDefinition.actorParameter = subset("actorParameter", PartUsage, 0, '*', None, _Behavior.parameter, Definition.usage)
ObjectiveMembership.ownedObjectiveRequirement = redefine(ObjectiveMembership, "ownedObjectiveRequirement", RequirementUsage, _FeatureMembership.ownedMemberFeature)
TransitionFeatureMembership.transitionFeature = redefine(TransitionFeatureMembership, "transitionFeature", _Step, _FeatureMembership.ownedMemberFeature)
EventOccurrenceUsage.eventOccurrence = derivedunion("eventOccurrence", OccurrenceUsage, lower=1, upper=1)
PerformActionUsage.performedAction = redefine(PerformActionUsage, "performedAction", ActionUsage, EventOccurrenceUsage.eventOccurrence)
StateUsage.entryAction = derivedunion("entryAction", ActionUsage, upper=1)
StateUsage.doAction = derivedunion("doAction", ActionUsage, upper=1)
StateUsage.exitAction = derivedunion("exitAction", ActionUsage, upper=1)
StateUsage.stateDefinition = redefine(StateUsage, "stateDefinition", _Behavior, ActionUsage.actionDefinition)
ExhibitStateUsage.exhibitedState = redefine(ExhibitStateUsage, "exhibitedState", StateUsage, PerformActionUsage.performedAction)
StateSubactionMembership.action = redefine(StateSubactionMembership, "action", ActionUsage, _FeatureMembership.ownedMemberFeature)
StateDefinition.entryAction = derivedunion("entryAction", ActionUsage, upper=1)
StateDefinition.doAction = derivedunion("doAction", ActionUsage, upper=1)
StateDefinition.exitAction = derivedunion("exitAction", ActionUsage, upper=1)
StateDefinition.state = subset("state", StateUsage, 0, '*', None, ActionDefinition.action)
TransitionUsage.source = derivedunion("source", ActionUsage, lower=1, upper=1)
TransitionUsage.target = derivedunion("target", ActionUsage, lower=1, upper=1)
TransitionUsage.triggerAction = subset("triggerAction", AcceptActionUsage, 0, '*', None, _Type.ownedFeature)
TransitionUsage.guardExpression = subset("guardExpression", _Expression, 0, '*', None, _Type.ownedFeature)
TransitionUsage.effectAction = subset("effectAction", ActionUsage, 0, '*', None, _Type.feature)
TransitionUsage.succession = subset("succession", _Succession, 1, 1, None, _Namespace.ownedMember)
UseCaseUsage.includedUseCase = derivedunion("includedUseCase", UseCaseUsage)
UseCaseUsage.useCaseDefinition = redefine(UseCaseUsage, "useCaseDefinition", UseCaseDefinition, CaseUsage.caseDefinition)
IncludeUseCaseUsage.useCaseIncluded = redefine(IncludeUseCaseUsage, "useCaseIncluded", UseCaseUsage, PerformActionUsage.performedAction)
UseCaseDefinition.includedUseCase = derivedunion("includedUseCase", UseCaseUsage)
AssignmentActionUsage.targetArgument = derivedunion("targetArgument", _Expression, upper=1)
AssignmentActionUsage.valueExpression = derivedunion("valueExpression", _Expression, upper=1)
AssignmentActionUsage.referent = subset("referent", _Feature, 1, 1, None, _Namespace.member)
LoopActionUsage.bodyAction = derivedunion("bodyAction", ActionUsage, lower=1, upper=1)
ForLoopActionUsage.seqArgument = derivedunion("seqArgument", _Expression, lower=1, upper=1)
ForLoopActionUsage.loopVariable = derivedunion("loopVariable", ReferenceUsage, lower=1, upper=1)
TerminateActionUsage.terminatedOccurrenceArgument = derivedunion("terminatedOccurrenceArgument", _Expression, upper=1)
AcceptActionUsage.receiverArgument = derivedunion("receiverArgument", _Expression, upper=1)
AcceptActionUsage.payloadArgument = derivedunion("payloadArgument", _Expression, upper=1)
AcceptActionUsage.payloadParameter = subset("payloadParameter", ReferenceUsage, 1, 1, None, Usage.nestedReference, _Step.parameter)
WhileLoopActionUsage.whileArgument = derivedunion("whileArgument", _Expression, lower=1, upper=1)
WhileLoopActionUsage.untilArgument = derivedunion("untilArgument", _Expression, upper=1)
SendActionUsage.receiverArgument = derivedunion("receiverArgument", _Expression, upper=1)
SendActionUsage.payloadArgument = derivedunion("payloadArgument", _Expression, lower=1, upper=1)
SendActionUsage.senderArgument = derivedunion("senderArgument", _Expression, upper=1)
IfActionUsage.elseAction = derivedunion("elseAction", ActionUsage, upper=1)
IfActionUsage.thenAction = derivedunion("thenAction", ActionUsage, lower=1, upper=1)
IfActionUsage.ifArgument = derivedunion("ifArgument", _Expression, lower=1, upper=1)
VariantMembership.ownedVariantUsage = redefine(VariantMembership, "ownedVariantUsage", Usage, _OwningMembership.ownedMemberElement)
PartUsage.partDefinition = subset("partDefinition", PartDefinition, 0, '*', None, ItemUsage.itemDefinition)
AnalysisCaseUsage.analysisCaseDefinition = redefine(AnalysisCaseUsage, "analysisCaseDefinition", AnalysisCaseDefinition, CaseUsage.caseDefinition)
AnalysisCaseUsage.resultExpression = subset("resultExpression", _Expression, 0, 1, None, _Type.ownedFeature)
AnalysisCaseDefinition.resultExpression = subset("resultExpression", _Expression, 0, 1, None, _Function.expression, _Type.ownedFeature)
PortConjugation.originalPortDefinition = redefine(PortConjugation, "originalPortDefinition", PortDefinition, _Conjugation.originalType)
PortConjugation.conjugatedPortDefinition = redefine(PortConjugation, "conjugatedPortDefinition", ConjugatedPortDefinition, _Conjugation.owningType, opposite="ownedPortConjugator")
PortDefinition.conjugatedPortDefinition = subset("conjugatedPortDefinition", ConjugatedPortDefinition, 0, 1, None, _Namespace.ownedMember)
ConjugatedPortDefinition.originalPortDefinition = redefine(ConjugatedPortDefinition, "originalPortDefinition", PortDefinition, _Element.owningNamespace, opposite="conjugatedPortDefinition")
ConjugatedPortDefinition.ownedPortConjugator = redefine(ConjugatedPortDefinition, "ownedPortConjugator", PortConjugation, _Type.ownedConjugator, opposite="conjugatedPortDefinition")
ConjugatedPortTyping.portDefinition = derivedunion("portDefinition", PortDefinition, lower=1, upper=1)
ConjugatedPortTyping.conjugatedPortDefinition = redefine(ConjugatedPortTyping, "conjugatedPortDefinition", ConjugatedPortDefinition, _FeatureTyping.type)
PortUsage.portDefinition = redefine(PortUsage, "portDefinition", PortDefinition, OccurrenceUsage.occurrenceDefinition)
ViewUsage.viewRendering = derivedunion("viewRendering", RenderingUsage, upper=1)
ViewUsage.viewDefinition = redefine(ViewUsage, "viewDefinition", ViewDefinition, PartUsage.partDefinition)
ViewUsage.satisfiedViewpoint = subset("satisfiedViewpoint", ViewpointUsage, 0, '*', None, Usage.nestedRequirement)
ViewUsage.exposedElement = subset("exposedElement", _Element, 0, '*', None, _Namespace.member)
ViewUsage.viewCondition = subset("viewCondition", _Expression, 0, '*', None, _Namespace.ownedMember)
ViewDefinition.viewRendering = derivedunion("viewRendering", RenderingUsage, upper=1)
ViewDefinition.view = subset("view", ViewUsage, 0, '*', None, Definition.usage)
ViewDefinition.satisfiedViewpoint = subset("satisfiedViewpoint", ViewpointUsage, 0, '*', None, Definition.ownedRequirement)
ViewDefinition.viewCondition = subset("viewCondition", _Expression, 0, '*', None, _Namespace.ownedMember)
RenderingUsage.renderingDefinition = redefine(RenderingUsage, "renderingDefinition", RenderingDefinition, PartUsage.partDefinition)
ViewpointDefinition.viewpointStakeholder = derivedunion("viewpointStakeholder", PartUsage)
RenderingDefinition.rendering = subset("rendering", RenderingUsage, 0, '*', None, Definition.usage)
ViewRenderingMembership.referencedRendering = derivedunion("referencedRendering", RenderingUsage, lower=1, upper=1)
ViewRenderingMembership.ownedRendering = redefine(ViewRenderingMembership, "ownedRendering", RenderingUsage, _FeatureMembership.ownedMemberFeature)
ViewpointUsage.viewpointStakeholder = derivedunion("viewpointStakeholder", PartUsage)
ViewpointUsage.viewpointDefinition = redefine(ViewpointUsage, "viewpointDefinition", ViewpointDefinition, RequirementUsage.requirementDefinition)
ConnectionUsage.connectionDefinition = redefine(ConnectionUsage, "connectionDefinition", _AssociationStructure, _Connector.association)
ConnectionDefinition.connectionEnd = redefine(ConnectionDefinition, "connectionEnd", Usage, _Association.associationEnd)
InterfaceUsage.interfaceDefinition = redefine(InterfaceUsage, "interfaceDefinition", InterfaceDefinition, ConnectionUsage.connectionDefinition)
InterfaceDefinition.interfaceEnd = redefine(InterfaceDefinition, "interfaceEnd", PortUsage, ConnectionDefinition.connectionEnd)
AllocationDefinition.allocation = subset("allocation", AllocationUsage, 0, '*', None, Definition.usage)
AllocationUsage.allocationDefinition = redefine(AllocationUsage, "allocationDefinition", AllocationDefinition, ConnectionUsage.connectionDefinition)
RequirementVerificationMembership.ownedRequirement = redefine(RequirementVerificationMembership, "ownedRequirement", RequirementUsage, RequirementConstraintMembership.ownedConstraint)
RequirementVerificationMembership.verifiedRequirement = redefine(RequirementVerificationMembership, "verifiedRequirement", RequirementUsage, RequirementConstraintMembership.referencedConstraint)
VerificationCaseDefinition.verifiedRequirement = derivedunion("verifiedRequirement", RequirementUsage)
VerificationCaseUsage.verifiedRequirement = derivedunion("verifiedRequirement", RequirementUsage)
VerificationCaseUsage.verificationCaseDefinition = subset("verificationCaseDefinition", VerificationCaseDefinition, 0, 1, None, CaseUsage.caseDefinition)
