#!/bin/bash
#
# Gaphor startup script
# Author: Arjan Molenaar <gaphor@gmail.com>
#
# Script is loosely inspired on bundle startup script from K-3D and Inkscape.
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# K-3D Modifications: Timothy M. Shead <tshead@k-3d.com>

PYVER="3.7"
MACOS="$(dirname $0)"
CONTENTS="$(dirname $MACOS)"
BIN="$CONTENTS/bin"

CFG="$HOME/.config/gaphor"

PYTHONHOME="${CONTENTS}/Frameworks/Python.framework/Versions/${PYVER}"
PYTHONPATH="${CONTENTS}/lib/python${PYVER}/site-packages"

mkdir -p "${CFG}"
GDK_PIXBUF_MODULE_FILE="${CFG}/gdk-pixbuf-2.0-loaders.cache"

"${BIN}/gdk-pixbuf-query-loaders" ../lib/gdk-pixbuf-2.0/2.10.0/loaders/* > "${GDK_PIXBUF_MODULE_FILE}"
export PYTHONHOME PYTHONPATH GDK_PIXBUF_MODULE_FILE

"${BIN}/python${PYVER}" "${BIN}/gaphor"
