#!/bin/bash
#
# Gaphor startup script
# Author: Arjan Molenaar <gaphor@gmail.com>
#
# Script is loosely inspired on bundle startup script from K-3D and Inkscape.
# Author: Aaron Voisine <aaron@voisine.org>
# Inkscape Modifications: Michael Wybrow <mjwybrow@users.sourceforge.net>
# K-3D Modifications: Timothy M. Shead <tshead@k-3d.com>

#cd "${0%/*}"

MACOS="$(dirname $0)"
CONTENTS="$(dirname $MACOS)"
RESOURCES="$CONTENTS/Resources"
BIN="$CONTENTS/bin"

CFG="$HOME/.local/share/gaphor"

PYTHONPATH="$CONTENTS/lib/python3.7"
#PYTHONPATH="$PYTHONPATH:$PYTHONPATH/site-packages:/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC"
GDK_PIXBUF_MODULE_FILE="$CFG/gdk-pixbuf-2.0-loaders.cache"

export PYTHONPATH GDK_PIXBUF_MODULE_FILE

# Because the bundle could be located anywhere at runtime, we have to
# create temporary copies of the GTK+/Gdk-Pixbuf/Pango configuration files
# that reflect our current location
#mkdir -p "$CFG/etc/gtk-2.0"
#cp -f "$RESOURCES/etc/gtk-2.0/im-multipress.conf" "$CFG/etc/gtk-2.0/im-multipress.conf"

mkdir -p "$CFG/lib/gdk-pixbuf-2.0/2.10.0"
sed -e 's|/usr/local|'"$CONTENTS|g" "$CONTENTS/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" > "$GDK_PIXBUF_MODULE_FILE"

"$BIN/python" "$BIN/gaphor"
