name: 'Create a Linux AppImage'
description: 'Freeze the app using PyInstaller and create an AppImage'
inputs:
  version:
    description: 'Gaphor version number'
    required: true
  github_token:
    description: 'GitHub token for uploading releases'
    required: true
  mainline_build:
    description: 'Build is performed on the main line'
    required: true
runs:
  using: composite
  steps:
    - name: Install Build Dependencies
      run: poetry install --only main,packaging --no-interaction
      shell: bash
    - name: Build AppImage
      env:
        GAPHOR_PKG_GTK: "3"
      run: |
        jhbuild shell
        poetry run poe package
        cd _packaging/appimage
        make dist
      shell: bash
    - name: Upload gaphor-${{ inputs.version }}-x86_64.AppImage
      uses: actions/upload-artifact@v3
      with:
        name: Gaphor-${{ inputs.version }}-x86_64.AppImage
        path: _packaging/dist/Gaphor-${{ inputs.version }}-x86_64.AppImage
    - name: Upload Release Assets
      if: inputs.mainline_build == 'true' && github.event_name == 'release'
      run: gh release upload ${{ github.event.release.tag_name }} _packaging/dist/* --clobber
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
