# This file is generated by profile_coder.py. DO NOT EDIT!

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Callable, List, Optional

from gaphor.core.modeling.collection import collection
from gaphor.core.modeling.element import Element
from gaphor.core.modeling.properties import (
    association,
    attribute,
    derived,
    derivedunion,
    enumeration,
    redefine,
    relation_many,
    relation_one,
)
from gaphor.UML import (
    Abstraction,
    AcceptEventAction,
    ActivityEdge,
    ActivityPartition,
    AddStructuralFeatureValueAction,
    Behavior,
    ChangeEvent,
    Class,
    Classifier,
    Comment,
    Connector,
    ConnectorEnd,
    DataType,
    Dependency,
    DirectedRelationship,
    Element,
    Feature,
    Generalization,
    InstanceSpecification,
    InvocationAction,
    NamedElement,
    ObjectNode,
    Operation,
    Optional,
    Parameter,
    ParameterSet,
    Port,
    Property,
    StructuralFeature,
    Trigger,
)


class AbstractRequirement(NamedElement):
    base_NamedElement: attribute[NamedElement]
    satisfiedBy: attribute[NamedElement]
    text: attribute[str]
    derived: attribute[AbstractRequirement]
    tracedTo: attribute[NamedElement]
    externalId: attribute[str]
    verifiedBy: attribute[NamedElement]
    master: attribute[AbstractRequirement]
    refinedBy: attribute[NamedElement]


class AcceptChangeStructuralFeatureEventAction(AcceptEventAction):
    pass


class ElementPropertyPath(Element):
    propertyPath: relation_one[None]


class AddFlowPropertyValueOnNestedPortAction(
    ElementPropertyPath, AddStructuralFeatureValueAction
):
    pass


class AdjuntProperty(Property):
    principal: relation_one[None]


class DirectedRelationshipPropertyPath(DirectedRelationship):
    targetContext: relation_one[None]
    sourceContext: relation_one[None]


class Allocate(DirectedRelationshipPropertyPath, Abstraction):
    pass


class AllocateActivityPartition(ActivityPartition):
    pass


class BindingConnector(Connector):
    pass


class Block(Class):
    isEncapsulated: attribute[int]


class EndPathMultiplicity(Property):
    pass


class BoundReference(EndPathMultiplicity):
    bindingPath: attribute[Property]
    boundend: attribute[ConnectorEnd]


class ChangeSructuralFeatureEvent(ChangeEvent):
    structuralFeature: relation_one[None]


class ClassifierBehaviorProperty(Property):
    pass


class Conform(Generalization):
    pass


class ConnectorProperty(Property):
    connector: attribute[Connector]


class ConstraintBlock(Block):
    pass


class Rate(ActivityEdge, Parameter):
    rate: attribute[InstanceSpecification]


class Continuous(Rate):
    pass


class ControlOperator(Behavior):
    pass


class Trace(DirectedRelationshipPropertyPath):
    pass


class Copy(Trace):
    pass


class DeriveReqt(Trace):
    pass


class DirectedFeature(Feature):
    featureDirection: attribute[None]


class Discrete(Rate):
    pass


class DistributedProperty(Property):
    pass


class ElementGroup(Comment):
    orderedMember: attribute[Element]
    size: attribute[int]
    criterion: attribute[str]
    member: attribute[Element]
    name: attribute[str]


class Expose(Dependency):
    pass


class FlowProperty(Property):
    direction: attribute[None]


class FullPort(Port):
    pass


class InterfaceBlock(Block):
    pass


class InvocationOnNestedPortAction(ElementPropertyPath, InvocationAction):
    onNestedPort: relation_one[None]


class NestedConnectorEnd(ElementPropertyPath, ConnectorEnd):
    pass


class NoBuffer(ObjectNode):
    pass


class Overwrite(ObjectNode):
    pass


class ParticipantProperty(Property):
    end: attribute[Property]


class Probability(ActivityEdge, ParameterSet):
    probability: attribute[str]


class Problem(Comment):
    pass


class PropertySpecificType(Classifier):
    pass


class ProxyPort(Port):
    pass


class Rationale(Comment):
    pass


class Refine(DirectedRelationshipPropertyPath):
    pass


class Requirement(AbstractRequirement, Class):
    pass


class Satisfy(Trace):
    pass


class Stakeholder(Classifier):
    concernList: attribute[Comment]
    concern: attribute[str]


class Tagged(Property):
    subsets: attribute[str]
    nonunique: attribute[bool]
    ordered: attribute[bool]


class TestCase(Behavior):
    pass


class TriggerOnNestedPort(ElementPropertyPath, Trigger):
    onNestedPort: relation_one[None]


class ValueType(DataType):
    unit: relation_one[None]


class Verify(Trace):
    pass


class View(Class):
    viewpoint: attribute[Viewpoint]
    stakeholder: attribute[Stakeholder]


class Viewpoint(Class):
    language: attribute[str]
    method: attribute[Behavior]
    presentation: attribute[str]
    purpose: attribute[str]
    concern: attribute[str]
    stakeholder: attribute[Stakeholder]
    concernList: attribute[Comment]


class _Refine:
    pass


class _Trace:
    pass
