# This file is generated by profile_coder.py. DO NOT EDIT!

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Callable, List, Optional

from gaphor.core.modeling.collection import collection
from gaphor.core.modeling.element import Element
from gaphor.core.modeling.properties import (
    association,
    attribute,
    derived,
    derivedunion,
    enumeration,
    redefine,
    relation_many,
    relation_one,
)
from gaphor.UML import (
    Abstraction,
    AcceptEventAction,
    ActivityEdge,
    ActivityPartition,
    AddStructuralFeatureValueAction,
    Behavior,
    ChangeEvent,
    Class,
    Classifier,
    Comment,
    Connector,
    ConnectorEnd,
    DataType,
    Dependency,
    DirectedRelationship,
    Element,
    Feature,
    Generalization,
    InstanceSpecification,
    InvocationAction,
    NamedElement,
    ObjectNode,
    Operation,
    Optional,
    Parameter,
    ParameterSet,
    Port,
    Property,
    StructuralFeature,
    Trigger,
)


class AbstractRequirement(NamedElement):
    externalId: attribute[str]
    base_NamedElement: relation_one[NamedElement]


class AcceptChangeStructuralFeatureEventAction(AcceptEventAction):
    pass


class ElementPropertyPath(Element):
    propertyPath: relation_many[None]


class AddFlowPropertyValueOnNestedPortAction(
    ElementPropertyPath, AddStructuralFeatureValueAction
):
    pass


class AdjuntProperty(Property):
    principal: relation_one[None]


class DirectedRelationshipPropertyPath(DirectedRelationship):
    sourceContext: relation_one[None]
    targetContext: relation_one[None]


class Allocate(DirectedRelationshipPropertyPath, Abstraction):
    pass


class AllocateActivityPartition(ActivityPartition):
    pass


class BindingConnector(Connector):
    pass


class Block(Class):
    isEncapsulated: attribute[int]


class EndPathMultiplicity(Property):
    pass


class BoundReference(EndPathMultiplicity):
    boundend: relation_many[ConnectorEnd]


class ChangeSructuralFeatureEvent(ChangeEvent):
    structuralFeature: relation_one[None]


class ClassifierBehaviorProperty(Property):
    pass


class Conform(Generalization):
    pass


class ConnectorProperty(Property):
    connector: relation_one[Connector]


class ConstraintBlock(Block):
    pass


class Rate(ActivityEdge, Parameter):
    rate: relation_many[InstanceSpecification]


class Continuous(Rate):
    pass


class ControlOperator(Behavior):
    pass


class Trace(DirectedRelationshipPropertyPath):
    pass


class Copy(Trace):
    pass


class DeriveReqt(Trace):
    pass


class DirectedFeature(Feature):
    featureDirection: relation_one[None]


class Discrete(Rate):
    pass


class DistributedProperty(Property):
    pass


class ElementGroup(Comment):
    name: attribute[str]
    orderedMember: relation_many[Element]


class Expose(Dependency):
    pass


class FlowProperty(Property):
    direction: relation_one[None]


class FullPort(Port):
    pass


class InterfaceBlock(Block):
    pass


class InvocationOnNestedPortAction(ElementPropertyPath, InvocationAction):
    onNestedPort: relation_many[None]


class NestedConnectorEnd(ElementPropertyPath, ConnectorEnd):
    pass


class NoBuffer(ObjectNode):
    pass


class Overwrite(ObjectNode):
    pass


class ParticipantProperty(Property):
    end_: relation_one[Property]


class Probability(ActivityEdge, ParameterSet):
    probability: attribute[str]


class Problem(Comment):
    pass


class PropertySpecificType(Classifier):
    pass


class ProxyPort(Port):
    pass


class Rationale(Comment):
    pass


class Refine(DirectedRelationshipPropertyPath):
    pass


class Requirement(AbstractRequirement, Class):
    pass


class Satisfy(Trace):
    pass


class Stakeholder(Classifier):
    concernList: relation_many[Comment]


class Tagged(Property):
    ordered: relation_many[bool]
    nonunique: relation_many[bool]
    subsets: attribute[str]


class TestCase(Behavior):
    pass


class TriggerOnNestedPort(ElementPropertyPath, Trigger):
    onNestedPort: relation_many[None]


class ValueType(DataType):
    unit: relation_one[None]


class Verify(Trace):
    pass


class View(Class):
    pass


class Viewpoint(Class):
    presentation: attribute[str]
    purpose: attribute[str]
    stakeholder: relation_many[Stakeholder]
    concernList: relation_many[Comment]
    language: attribute[str]


class _Refine:
    pass


class _Trace:
    pass


AbstractRequirement.externalId = attribute("externalId", str)
Block.isEncapsulated = attribute("isEncapsulated", int)
ElementGroup.name = attribute("name", str)
Probability.probability = attribute("probability", str)
Tagged.subsets = attribute("subsets", str)
Viewpoint.presentation = attribute("presentation", str)
Viewpoint.purpose = attribute("purpose", str)
Viewpoint.language = attribute("language", str)
