name: "Pull Request Labeler"
on:
  # pull_request_target is not considered safe, but only updates PRs in our case.
- pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          *.githubusercontent.com:443
          ghcr.io

    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
