name: "Pull Request Labeler"
on:
  # pull_request_target is not considered safe, but only updates PRs in our case.
- pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          *.githubusercontent.com:443
          ghcr.io

    - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: false
