name: Lint

on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published, prereleased]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
      - name: Lint with Pre-commit
        uses: pre-commit/action@v2.0.3
