name: Release Drafter

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            *.githubusercontent.com:443
            ghcr.io
      - uses: release-drafter/release-drafter@563bf132657a13ded0b01fcb723c5a58cdd824e2 # v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
