name: Release Drafter

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  update-release-draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            *.githubusercontent.com:443
            ghcr.io
      - uses: release-drafter/release-drafter@139054aeaa9adc52ab36ddf67437541f039b88e2 # v7.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
